template_name = "default"
rokit_tools = ["rojo", "wally", "wally-package-types", "1Axen/blink"]

[[wally.shared]]
name = "t"
origin = "osyrisrblx/t@3.1.1"

[[wally.shared]]
name = "Signal"
origin = "sleitnick/signal@2.0.3"

[[wally.shared]]
name = "Fusion"
origin = "elttob/fusion@0.3.0"

[[wally.shared]]
name = "onboot"
origin = "gigahd/onboot@0.5.1"

[[wally.server]]
name = "ProfileStore"
origin = "lm-loleris/profilestore@1.0.3"
